services:
  nginx:
    container_name: "nginx"
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    volumes:
      - /var/www/html:/usr/share/nginx/html
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: "mariadb"
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    restart: always

  wordpress:
    container_name: "wordpress"
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    restart: always