services:
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    expose:
      - "443"
    volumes:
      - ./nginx:/var/www/html/wordpress
    networks:
      - inception-network

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file: .env
    # secrets:
    #   - my_db_user
    #   - my_db_password
    #   - my_db_root_password
    networks:
      - inception-network

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    volumes:
      - ./nginx:/var/www/html/wordpress
    env_file : .env
    expose:
       - "9000"
    networks:
      - inception-network
    depends_on:
      - mariadb

volumes:
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/llarue/data/wordpress
  mariadb:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: /home/llarue/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/llarue/data/wordpress

networks:
  inception-network:
    driver: bridge
    driver_opts:
      type: none
      o: bind
      device: /home/llarue/data/wordpress

# secrets:
#   my_db_user:
#     file: ../secrets/db_user.txt
#   my_db_passwd:
#     file: ../secrets/db_password.txt
#   my_db_root_passwd:
#     file: ../secrets/db_root_password.txt
  # my_wp_admin:
  #   file: ../secrets/wp_admin.txt
  # my_wp_admin_passwd:
  #   file: ../secrets/wp_admin_password.txt
  # my_wp_admin_email:
  #   file: ../secrets/wp_admin_email.txt
  # my_wp_user:
  #   file: ../secrets/wp_user.txt
  # my_wp_passwd:
  #   file: ../secrets/wp_password.txt
  # my_wp_email:
  #   file: ../secrets/wp_email.txt