services:
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    image: nginx:inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: unless-stopped
    networks:
      - inception-network
    depends_on:
      - wordpress

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    image: mariadb:inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secrets/db_root_password
      MYSQL_PASSWORD_FILE: /secrets/db_password
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception-network

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    image: wordpress:inception
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file : .env
    environment:
      MYSQL_PASSWORD_FILE: /secrets/db_password
    secrets:
      - db_password
    expose:
       - "9000"
    restart: unless-stopped
    networks:
      - inception-network
    depends_on:
      - mariadb

volumes:
  mariadb:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: /home/llarue/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/llarue/data/wordpress

networks:
  inception-network:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt