services:
  nginx:
    container_name: "nginx"
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    container_name: "mariadb"
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    restart: always

  wordpress:
    container_name: "wordpress"
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    restart: always