services:
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    expose:
      - "443"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception-network

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception-network

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file : .env
    expose:
       - "9000"
    networks:
      - inception-network
    depends_on:
      - mariadb

volumes:
  mariadb:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: /home/llarue/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/llarue/data/wordpress

networks:
  inception-network:
    driver: bridge