services:
  nginx:
    container_name: "nginx"
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx:./requirements/nginx/conf/
    restart: always

  mariadb:
    container_name: "mariadb"
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    restart: always

  wordpress:
    container_name: "wordpress"
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
      volumes:
      - ./nginx:./requirements/nginx/conf/
    restart: always