services:
  nginx:
    container_name: "nginx"
    build:
      context: ./
      dockerfile: ./srcs/requirements/nginx/Dockerfile
    ports:
      - 8080:8080
    restart: always

  mariadb:
    container_name: "mariadb"
    build:
      context: ./
      dockerfile: ./srcs/requirements/mariadb/Dockerfile
    restart: always

  wordpress:
    container_name: "wordpress"
    build:
      context: ./
      dockerfile: ./srcs/requirements/wordpress/Dockerfile
    restart: always