services:
  # nginx:
  #   container_name: "nginx"
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./nginx:/var/www/html
  #   networks:
  #     - inception

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: .env
    # secrets:
    #   - my_db_user
    #   - my_db_password
    #   - my_db_root_password
    networks:
      - inception

  # wordpress:
  #   container_name: "wordpress"
  #   build: ./requirements/wordpress/
  #   volumes:
  #     - ./nginx:/var/www/html
  #   networks:
  #     - inception

# volmues:
#   nginx:
#     driver: local
#   mariadb:
#     driver: local
#   wordpress:
#     driver: local

networks:
  inception:
    driver: bridge

# secrets:
#   my_db_user:
#     file: ../secrets/db_user.txt
#   my_db_passwd:
#     file: ../secrets/db_password.txt
#   my_db_root_passwd:
#     file: ../secrets/db_root_password.txt
  # my_wp_admin:
  #   file: ../secrets/wp_admin.txt
  # my_wp_admin_passwd:
  #   file: ../secrets/wp_admin_password.txt
  # my_wp_admin_email:
  #   file: ../secrets/wp_admin_email.txt
  # my_wp_user:
  #   file: ../secrets/wp_user.txt
  # my_wp_passwd:
  #   file: ../secrets/wp_password.txt
  # my_wp_email:
  #   file: ../secrets/wp_email.txt