services:
  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx:/var/www/html

  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    volumes:
      - ./nginx:/var/www/html