services:
  nginx:
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:8080

  mariadb:
    container_name: mariadb
    build:
      dockerfile: ./mariadb/Dockerfile

  wordpress:
    container_name: wordpress
    build:
      dockerfile: ./wordpress/Dockerfile