services:
  nginx:
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile

  mariadb:
    container_name: mariadb
    build:
      dockerfile: ./mariadb/Dockerfile

  wordpress:
    container_name: wordpress
    build:
      dockerfile: ./wordpress/Dockerfile