services:
  nginx:
    container_name: "nginx"
    build:
      context: ./
      dockerfile: ./requirements/nginx/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 8080:8080
    restart: always

  mariadb:
    container_name: "mariadb"
    build:
      context: ./
      dockerfile: ./requirements/mariadb/Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    container_name: "wordpress"
    build:
      context: ./
      dockerfile: ./requirements/wordpress/Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    restart: always